### ISSUE TITLE
Fehler im else Zweig

### ISSUE THREAD

**Issue by Zwer2k** [svenson08/ftui-weekdaytimer-widget#1]
Hallo,

im else Zweig ab Zeile 558 ist ein Fehler.

Fehlermeldung:

> TypeError: profileparts[2] is undefined

Der Fehler kommt wenn der Timer z.B. wie folgt definiert ist:

> Wohnzimmer_Rollladen 07:00|on Mo,Tu,Th-Fr|16:00|off

Hier muss vermutlich an allen stellen profileparts[2] durch profileparts[1] ersetzt werden:

```
} else {
                        profile.push(profileparts[1]);
                        if (widget_wdtimer.wdtimer_multiArrayindexOf(arr_cmdlist,profileparts[2]) == -1) { //Fehlende Befehle in Befehlliste aufnehmen
                            var arr_cmd = new Array();      
                            arr_cmd.push(profileparts[2].toUpperCase()+'*', profileparts[2]);                    
                            arr_cmdlist.push(arr_cmd);
                        }
}
```

Gruß
Jurij

**Comment by svenson08** [comment]
Danke, hab den Fehler behoben.
