### ISSUE TITLE
Kleiner Fehler in der README

### ISSUE THREAD

**Issue by Zwer2k** [svenson08/ftui-weekdaytimer-widget#2]
Zeile

`<link rel="stylesheet" href="/fhem/tablet/css/fhem-tablet-ui-user.css" />
`
sollte glaube ich
`<link rel="stylesheet" href="/fhem/tablet/css/fhem-tablet-ui-wdtimer.css" />
`
heißen.

Gruß
Jurij

**Comment by svenson08** [comment]
Danke, habs geändert.
